### ISSUE TITLE
Production Checklist

### ISSUE THREAD

**Issue by noobling** [noobling/david-learns#29]
- [ ] Implemented appropriate Security Headers https://securityheaders.com/
- [ ] Loads okay on a slow connection
- [ ] Lighthouse audit
- [ ] Continual monitoring of vulnerabilities https://snyk.io/
- [ ] Catching errors https://sentry.io/welcome/
