### ISSUE TITLE
Improve our backend 

### ISSUE THREAD

**Issue by noobling** [noobling/david-learns#33]
## Context
Backend in this context refers to all our custom lambda functions that interact with all our AWS services e.g. with S3, AppSync and SES

## Challenge
Right now it isn't a great experience working with the backend because
- [ ] Slow to test changes
- [ ] Duplicated code across our various projects e.g. scripts, sim-api, admin-api, app
- [ ] No proactive telemetry on important information such as exceptions
- [ ] We have to define constants that can are already being pre generated by amplify
- [ ] No strong coding conventions

This isn't a problem since the backend code is relatively small compared to the frontend but these issues will become more pronounced as the code naturally grows

## Solution
- [ ] Add typescript
- [ ] Add sentry or similar service
- [ ] Research and implement coding conventions that work well with lambda functions
- [ ] Investigate and implement monorepo tools that help with code sharing e.g. https://nx.dev/
